repos:
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
            pass_filenames: false
